version: '3.7'

services:

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/backend 
      - ./frontend:/var/www/frontend
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - backend
      - frontend
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'appuser'
      MYSQL_PASSWORD: 'appuser'
    volumes:
      - dbdata:/var/lib/mysql 
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

volumes:
  dbdata:
    driver: local
networks:
  app-network:
    driver: bridge